export const stages = [
  {
    title: 'Middle Layer, move to right',
    description: 'Insert a top center piece into the right side of the middle layer.',
    steps: [
      {name: 'U', order: [0, 6]},
      {name: 'R', order: [1]},
      {name: 'Ui', order: [2, 4]},
      {name: 'Ri', order: [3]},
      {name: 'Ui', order: [2, 4]},
      {name: 'Fi', order: [5]},
      {name: 'U', order: [0, 6]},
      {name: 'F', order: [7]},
    ],
  },
  {
    title: 'Middle Layer, move to left',
    description: 'Insert a top center piece into the left side of the middle layer',
    steps: [
      {name: 'Ui', order: [0, 6]},
      {name: 'Li', order: [1]},
      {name: 'U', order: [2, 4]},
      {name: 'L', order: [3]},
      {name: 'U', order: [2, 4]},
      {name: 'F', order: [5]},
      {name: 'Ui', order: [0, 6]},
      {name: 'Fi', order: [7]},
    ],
  },
  {
    title: 'Creating Yellow Cross',
    description: 'Generate the yellow cross.',
    steps: [
      {name: 'F', order: [0]},
      {name: 'R', order: [1]},
      {name: 'U', order: [2]},
      {name: 'Ri', order: [3]},
      {name: 'Ui', order: [4]},
      {name: 'Fi', order: [5]},
    ],
  },
  {
    title: 'Yellow Edges',
    description: 'Move yellow edge pieces to their correct location',
    steps: [
      {name: 'R', order: [0, 4]},
      {name: 'U', order: [1, 3, 7]},
      {name: 'Ri', order: [2, 6]},
      {name: 'U', order: [1, 3, 7]},
      {name: 'R', order: [0, 4]},
      {name: 'U2', order: [5]},
      {name: 'Ri', order: [2, 6]},
      {name: 'U', order: [1, 3, 7]},
    ],
  },
  {
    title: 'Alligning Yellow corner pieces',
    description: 'Align all the corner pieces to their correct location',
    steps: [
      {name: 'U', order: [0, 4]},
      {name: 'R', order: [1]},
      {name: 'Ui', order: [2, 6]},
      {name: 'Li', order: [3]},
      {name: 'U', order: [0, 4]},
      {name: 'Ri', order: [5]},
      {name: 'Ui', order: [2, 6]},
      {name: 'L', order: [7]},
    ],
  },
  {
    title: 'Orient yellow corners',
    description: 'Last step to finish the cube.',
    steps: [
      {name: 'Ri', order: [0]},
      {name: 'Di', order: [1]},
      {name: 'R', order: [2]},
      {name: 'D', order: [3]},
    ],
  },
]
